### PR TITLE
Update for 0.16

### PR DESCRIPTION
**Pull request by mgold**

### CODE REVIEW

**Comment by JoeyEremondi** [comment]
Would this maybe be a good library to transfer to elm-community?

**Comment by mgold** [comment]
Possibly, if you're not interested in maintaining it.

**Comment by JoeyEremondi** [comment]
I'm still interested in maintaining it, it's more that I'm willing to share control, so that not every change has to go through me.

**Comment by mgold** [comment]
Seem reasonable. And it's simpler since it's not published.

**Comment by JoeyEremondi** [comment]
Yeah, it never made the Native whitelist.

**Comment by mgold** [comment]
What's so special that can't be done in Elm? Just glancing over it, is it keeping `benchmarkN` well-typed for everything? Or does benchmark.js do something very helpful? I'd also be okay with the "library hands you something to send out a port" solution here.

**Comment by JoeyEremondi** [comment]
There's nothing particularly special, but it would likely require a complete rewrite. Basically, my view was that I didn't want to deal with worrying about timers, or accuracy, or sampling, so the library is really just a thin wrapper around Benchmark.js. It's what people are used to, since jsperf uses it.

I have no opposition to a pure Elm solution, but I don't know if I'm qualified to deal with the lower-level issues to write it. 

It's also entirely possible that benchmark.js doesn't deal with these things properly, in which case we'd have nothing to lose by going pure Elm.

**Comment by mgold** [comment]
You'd probably need a task-based library to get the exact current time in order to time the benchmarks.

I think it's fine how it is, might just need a few things in the README.

**Pull request merged**
